name:                haskell-bot
version:             0.1.0.0
github:              "shun-shobon/haskell-bot"
license:             MIT
author:              "Shuntaro Nishizawa"
maintainer:          "Shuntaro Nishizawa"
copyright:           "2019 Shuntaro Nishizawa"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Haskell練習用Botです。

dependencies:
  - base >= 4.7 && < 5
  - text
  - discord-haskell

library:
  source-dirs: src

executables:
  haskell-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-bot

tests:
  haskell-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-bot
